import multtestlib
import functions


def main():
    for i in range(0, 20):
        with multtestlib.Pool(4) as pool:
            pool.starmap(multtestlib.test_func,
                         [(functions.slow_function, 50, '', 50),
                          (functions.slow_function, 51, '', 51),
                          (functions.slow_function, 52, '', 52),
                          (functions.slow_function, 53, '', 53),
                          (functions.slow_function, 54, '', 54),
                          (functions.slow_function, 55, '', 55),
                          (functions.slow_function, 56, '', 56),
                          (functions.slow_function, 57, '', 57),
                          (functions.slow_function, 58, '', 58),
                          (functions.slow_function, 59, '', 59),
                          (functions.slow_function, 60, '', 60),
                          (functions.slow_function, 61, '', 61),
                          (functions.slow_function, 62, '', 62),
                          (functions.slow_function, 63, '', 63),
                          (functions.slow_function, 64, '', 64),
                          (functions.slow_function, 65, '', 65),
                          (functions.slow_function, 66, '', 66),
                          (functions.slow_function, 67, '', 67),
                          (functions.slow_function, 68, '', 68),
                          (functions.slow_function, 69, '', 69),
                          (functions.slow_function, 70, '', 70),
                          (functions.slow_function, 71, '', 71),
                          (functions.slow_function, 72, '', 72),
                          (functions.slow_function, 73, '', 73),
                          (functions.slow_function, 74, '', 74),
                          (functions.slow_function, 75, '', 75),
                          (functions.slow_function, 76, '', 76),
                          (functions.slow_function, 77, '', 77),
                          (functions.slow_function, 78, '', 78),
                          (functions.slow_function, 79, '', 79),
                          (functions.slow_function, 80, '', 80),
                          (functions.slow_function, 81, '', 81),
                          (functions.slow_function, 82, '', 82),
                          (functions.slow_function, 83, '', 83),
                          (functions.slow_function, 84, '', 84),
                          (functions.slow_function, 85, '', 85),
                          (functions.slow_function, 86, '', 86),
                          (functions.slow_function, 87, '', 87),
                          (functions.slow_function, 88, '', 88),
                          (functions.slow_function, 89, '', 89),
                          (functions.slow_function, 90, '', 90),
                          (functions.slow_function, 91, '', 91),
                          (functions.slow_function, 92, '', 92),
                          (functions.slow_function, 93, '', 93),
                          (functions.slow_function, 94, '', 94),
                          (functions.slow_function, 95, '', 95),
                          (functions.slow_function, 96, '', 96),
                          (functions.slow_function, 97, '', 97),
                          (functions.slow_function, 98, '', 98),
                          (functions.slow_function, 99, '', 99),
                          (functions.slow_function, 100, '', 100),
                          (functions.slow_function, 101, '', 101),
                          (functions.slow_function, 102, '', 102),
                          (functions.slow_function, 103, '', 103),
                          (functions.slow_function, 104, '', 104),
                          (functions.slow_function, 105, '', 105),
                          (functions.slow_function, 106, '', 106),
                          (functions.slow_function, 107, '', 107),
                          (functions.slow_function, 108, '', 108),
                          (functions.slow_function, 109, '', 109),
                          (functions.slow_function, 110, '', 110),
                          (functions.slow_function, 111, '', 111),
                          (functions.slow_function, 112, '', 112),
                          (functions.slow_function, 113, '', 113),
                          (functions.slow_function, 114, '', 114),
                          (functions.slow_function, 115, '', 115),
                          (functions.slow_function, 116, '', 116),
                          (functions.slow_function, 117, '', 117),
                          (functions.slow_function, 118, '', 118),
                          (functions.slow_function, 119, '', 119),
                          (functions.slow_function, 120, '', 120),
                          (functions.slow_function, 121, '', 121),
                          (functions.slow_function, 122, '', 122),
                          (functions.slow_function, 123, '', 123),
                          (functions.slow_function, 124, '', 124),
                          (functions.slow_function, 125, '', 125),
                          (functions.slow_function, 126, '', 126),
                          (functions.slow_function, 127, '', 127),
                          (functions.slow_function, 128, '', 128),
                          (functions.slow_function, 129, '', 129),
                          (functions.slow_function, 130, '', 130),
                          (functions.slow_function, 131, '', 131),
                          (functions.slow_function, 132, '', 132),
                          (functions.slow_function, 133, '', 133),
                          (functions.slow_function, 134, '', 134),
                          (functions.slow_function, 135, '', 135),
                          (functions.slow_function, 136, '', 136),
                          (functions.slow_function, 137, '', 137),
                          (functions.slow_function, 138, '', 138),
                          (functions.slow_function, 139, '', 139),
                          (functions.slow_function, 140, '', 140),
                          (functions.slow_function, 141, '', 141),
                          (functions.slow_function, 142, '', 142),
                          (functions.slow_function, 143, '', 143),
                          (functions.slow_function, 144, '', 144),
                          (functions.slow_function, 145, '', 145),
                          (functions.slow_function, 146, '', 146),
                          (functions.slow_function, 147, '', 147),
                          (functions.slow_function, 148, '', 148),
                          (functions.slow_function, 149, '', 149),
                          ])


if __name__ == "__main__":
    multtestlib.init()
    multtestlib.freeze_support()
    main()
    multtestlib.end()
